[package]
name = "stracciatella_c_api"
version = "0.1.0"
authors = ["Stefan Lau <github@stefanlau.com>"]
edition = "2018"
workspace = ".."

[lib]
crate-type = ["staticlib"]

[dependencies]
byteorder = "1.3.1"
hex = "0.3.2"
libc = "0.2"
log = "0.4"
stracciatella = { path = "../stracciatella" }
tempfile = "3.0"

[target.'cfg(target_os = "android")'.dependencies.jni]
version = "0.14"

[build-dependencies]
cbindgen = "0.13, ~0.13.2"
